/**
 * Local medication autocomplete catalog.
 *
 * Canonical generic names are stored in `label`; brand names, regional names,
 * and common aliases are stored as synonyms/search terms for fuzzy search.
 * Categories support supplement interaction checks.
 */

/**
 * @typedef {{
 *   id: string;
 *   name: string;
 *   label: string;
 *   category: string;
 *   synonyms: string[];
 *   search_terms: string[];
 *   common: boolean;
 * }} MedicationGeneric
 */

function normalizeMedId(value) {
  return normalizeMedToken(value).replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function m(name, category, synonyms = [], common = false) {
  const label = normalizeMedToken(name);
  const cleanSynonyms = synonyms.map(normalizeMedToken).filter(Boolean);
  const searchTerms = Array.from(new Set([label, ...cleanSynonyms]));
  return {
    id: normalizeMedId(label),
    name: label,
    label,
    category,
    synonyms: cleanSynonyms,
    search_terms: searchTerms,
    common,
  };
}

/** @type {MedicationGeneric[]} */
export const MEDICATION_GENERICS = [
  m("acetaminophen", "pain", ["paracetamol", "tylenol", "calpol", "crocin"], true),
  m("ibuprofen", "pain", ["advil", "brufen", "nurofen"], true),
  m("aspirin", "antiplatelet", ["ecosprin", "disprin", "bayer aspirin"], true),
  m("naproxen", "pain", ["naprosyn", "aleve"], true),
  m("diclofenac", "pain", ["voltaren", "voveran"], true),
  m("aceclofenac", "pain", ["hifenac", "zerodol"], true),
  m("etoricoxib", "pain", ["arcoxia"], true),
  m("celecoxib", "pain", ["celebrex"], true),
  m("meloxicam", "pain", ["mobic"]),
  m("indomethacin", "pain", ["indocin"]),
  m("ketorolac", "pain", ["toradol"]),
  m("piroxicam", "pain", ["feldene"]),
  m("mefenamic acid", "pain", ["ponstan", "meftal"]),
  m("tramadol", "opioid", ["ultram"], true),
  m("codeine", "opioid", ["codeine phosphate"], true),
  m("morphine", "opioid", ["ms contin", "oramorph"]),
  m("oxycodone", "opioid", ["oxycontin", "percocet"]),
  m("hydrocodone", "opioid", ["vicodin", "norco"]),
  m("fentanyl", "opioid", ["duragesic"]),
  m("buprenorphine", "opioid", ["subutex", "butrans"]),
  m("tapentadol", "opioid", ["nucynta"]),
  m("naloxone", "opioid_antagonist", ["narcan"]),
  m("naltrexone", "opioid_antagonist", ["revia", "vivitrol"]),
  m("lidocaine", "local_anesthetic", ["lignocaine", "xylocaine"]),
  m("benzocaine", "local_anesthetic", ["orajel"]),
  m("capsaicin", "pain", ["zostrix"]),
  m("metformin", "antidiabetic", ["glucophage", "glycomet"], true),
  m("glimepiride", "antidiabetic", ["amaryl"], true),
  m("gliclazide", "antidiabetic", ["diamicron"], true),
  m("glipizide", "antidiabetic", ["glucotrol"]),
  m("glyburide", "antidiabetic", ["glibenclamide", "diabeta"]),
  m("insulin", "antidiabetic", ["novorapid", "lantus", "humalog"], true),
  m("insulin glargine", "antidiabetic", ["lantus", "basaglar", "toujeo"], true),
  m("insulin aspart", "antidiabetic", ["novorapid", "novolog"], true),
  m("insulin lispro", "antidiabetic", ["humalog"]),
  m("insulin detemir", "antidiabetic", ["levemir"]),
  m("insulin degludec", "antidiabetic", ["tresiba"]),
  m("regular insulin", "antidiabetic", ["humulin r", "novolin r"]),
  m("nph insulin", "antidiabetic", ["humulin n", "novolin n"]),
  m("semaglutide", "antidiabetic", ["ozempic", "rybelsus", "wegovy"], true),
  m("liraglutide", "antidiabetic", ["victoza", "saxenda"], true),
  m("dulaglutide", "antidiabetic", ["trulicity"], true),
  m("exenatide", "antidiabetic", ["byetta", "bydureon"]),
  m("tirzepatide", "antidiabetic", ["mounjaro", "zepbound"]),
  m("empagliflozin", "antidiabetic", ["jardiance"], true),
  m("dapagliflozin", "antidiabetic", ["forxiga", "farxiga"], true),
  m("canagliflozin", "antidiabetic", ["invokana"]),
  m("ertugliflozin", "antidiabetic", ["steglatro"]),
  m("sitagliptin", "antidiabetic", ["januvia"], true),
  m("vildagliptin", "antidiabetic", ["galvus"], true),
  m("linagliptin", "antidiabetic", ["trajenta", "tradjenta"], true),
  m("saxagliptin", "antidiabetic", ["onglyza"]),
  m("alogliptin", "antidiabetic", ["nesina"]),
  m("pioglitazone", "antidiabetic", ["actos"]),
  m("rosiglitazone", "antidiabetic", ["avandia"]),
  m("acarbose", "antidiabetic", ["precose", "glucobay"]),
  m("repaglinide", "antidiabetic", ["prandin"]),
  m("nateglinide", "antidiabetic", ["starlix"]),
  m("lisinopril", "ace_inhibitor", ["zestril", "prinivil"], true),
  m("enalapril", "ace_inhibitor", ["vasotec", "envas"], true),
  m("ramipril", "ace_inhibitor", ["altace", "cardace"], true),
  m("captopril", "ace_inhibitor", ["capoten"], true),
  m("perindopril", "ace_inhibitor", ["coversyl"], true),
  m("benazepril", "ace_inhibitor", ["lotensin"]),
  m("fosinopril", "ace_inhibitor", ["monopril"]),
  m("quinapril", "ace_inhibitor", ["accupril"]),
  m("trandolapril", "ace_inhibitor", ["mavik"]),
  m("losartan", "arb", ["cozaar"], true),
  m("valsartan", "arb", ["diovan"], true),
  m("telmisartan", "arb", ["micardis", "telma"], true),
  m("olmesartan", "arb", ["benicar", "olmezest"], true),
  m("irbesartan", "arb", ["avapro"]),
  m("candesartan", "arb", ["atacand"]),
  m("azilsartan", "arb", ["edarbi"]),
  m("eprosartan", "arb", ["teveten"]),
  m("amlodipine", "calcium_channel_blocker", ["norvasc", "amlong"], true),
  m("nifedipine", "calcium_channel_blocker", ["adalat", "procardia"], true),
  m("felodipine", "calcium_channel_blocker", ["plendil"]),
  m("diltiazem", "calcium_channel_blocker", ["cardizem", "tiazac"]),
  m("verapamil", "calcium_channel_blocker", ["calan", "isoptin"]),
  m("cilnidipine", "calcium_channel_blocker", ["cilacar"]),
  m("lercanidipine", "calcium_channel_blocker", ["zanidip"]),
  m("propranolol", "beta_blocker", ["inderal"], true),
  m("atenolol", "beta_blocker", ["tenormin"], true),
  m("metoprolol", "beta_blocker", ["lopressor", "toprol"], true),
  m("bisoprolol", "beta_blocker", ["zebeta", "concor"], true),
  m("carvedilol", "beta_blocker", ["coreg"], true),
  m("nebivolol", "beta_blocker", ["bystolic", "nebicard"]),
  m("labetalol", "beta_blocker", ["trandate"]),
  m("sotalol", "beta_blocker", ["betapace"]),
  m("hydrochlorothiazide", "thiazide_diuretic", ["hctz", "microzide"], true),
  m("chlorthalidone", "thiazide_diuretic", ["thalitone"]),
  m("indapamide", "thiazide_diuretic", ["lozol", "natrilix"]),
  m("furosemide", "loop_diuretic", ["lasix"], true),
  m("torsemide", "loop_diuretic", ["demadex"], true),
  m("bumetanide", "loop_diuretic", ["bumex"]),
  m("spironolactone", "k_sparing_diuretic", ["aldactone"], true),
  m("eplerenone", "k_sparing_diuretic", ["inspra"], true),
  m("amiloride", "k_sparing_diuretic", ["midamor"], true),
  m("triamterene", "k_sparing_diuretic", ["dyrenium"], true),
  m("atorvastatin", "statin", ["lipitor", "atorva"], true),
  m("rosuvastatin", "statin", ["crestor", "rosuvas"], true),
  m("simvastatin", "statin", ["zocor"], true),
  m("pravastatin", "statin", ["pravachol"]),
  m("lovastatin", "statin", ["mevacor"]),
  m("fluvastatin", "statin", ["lescol"]),
  m("pitavastatin", "statin", ["livalo"]),
  m("ezetimibe", "lipid_lowering", ["zetia"]),
  m("fenofibrate", "lipid_lowering", ["tricor"]),
  m("gemfibrozil", "lipid_lowering", ["lopid"]),
  m("niacin", "lipid_lowering", ["niaspan"]),
  m("evolocumab", "lipid_lowering", ["repatha"]),
  m("alirocumab", "lipid_lowering", ["praluent"]),
  m("digoxin", "cardiac_glycoside", ["lanoxin"], true),
  m("amiodarone", "antiarrhythmic", ["cordarone", "pacerone"]),
  m("dronedarone", "antiarrhythmic", ["multaq"]),
  m("flecainide", "antiarrhythmic", ["tambocor"]),
  m("propafenone", "antiarrhythmic", ["rythmol"]),
  m("nitroglycerin", "nitrate", ["glyceryl trinitrate", "nitrostat"], true),
  m("isosorbide mononitrate", "nitrate", ["imdur"], true),
  m("isosorbide dinitrate", "nitrate", ["isordil"]),
  m("ranolazine", "antianginal", ["ranexa"]),
  m("ivabradine", "antianginal", ["corlanor"]),
  m("hydralazine", "vasodilator", ["apresoline"]),
  m("minoxidil", "vasodilator", ["loniten", "rogaine"]),
  m("clonidine", "antihypertensive", ["catapres"]),
  m("methyldopa", "antihypertensive", ["aldomet"]),
  m("prazosin", "alpha_blocker", ["minipress"]),
  m("doxazosin", "alpha_blocker", ["cardura"]),
  m("terazosin", "alpha_blocker", ["hytrin"]),
  m("sacubitril valsartan", "heart_failure", ["entresto"]),
  m("warfarin", "anticoagulant", ["coumadin"], true),
  m("heparin", "anticoagulant", ["unfractionated heparin"], true),
  m("enoxaparin", "anticoagulant", ["clexane", "lovenox"], true),
  m("dalteparin", "anticoagulant", ["fragmin"]),
  m("fondaparinux", "anticoagulant", ["arixtra"]),
  m("dabigatran", "anticoagulant", ["pradaxa"], true),
  m("rivaroxaban", "anticoagulant", ["xarelto"], true),
  m("apixaban", "anticoagulant", ["eliquis"], true),
  m("edoxaban", "anticoagulant", ["savaysa", "lixiana"]),
  m("clopidogrel", "antiplatelet", ["plavix"], true),
  m("ticagrelor", "antiplatelet", ["brilinta"], true),
  m("prasugrel", "antiplatelet", ["effient"]),
  m("dipyridamole", "antiplatelet", ["persantine"]),
  m("cilostazol", "antiplatelet", ["pletal"]),
  m("sertraline", "ssri", ["zoloft"], true),
  m("fluoxetine", "ssri", ["prozac"], true),
  m("escitalopram", "ssri", ["lexapro", "nexito"], true),
  m("citalopram", "ssri", ["celexa"]),
  m("paroxetine", "ssri", ["paxil"], true),
  m("fluvoxamine", "ssri", ["luvox"]),
  m("venlafaxine", "snri", ["effexor"]),
  m("desvenlafaxine", "snri", ["pristiq"]),
  m("duloxetine", "snri", ["cymbalta"]),
  m("bupropion", "antidepressant", ["wellbutrin", "zyban"], true),
  m("mirtazapine", "antidepressant", ["remeron"], true),
  m("trazodone", "antidepressant", ["desyrel"]),
  m("vortioxetine", "antidepressant", ["trintellix"]),
  m("vilazodone", "antidepressant", ["viibryd"]),
  m("amitriptyline", "tricyclic", ["elavil"], true),
  m("nortriptyline", "tricyclic", ["pamelor"], true),
  m("imipramine", "tricyclic", ["tofranil"]),
  m("clomipramine", "tricyclic", ["anafranil"]),
  m("doxepin", "tricyclic", ["silenor"]),
  m("alprazolam", "benzodiazepine", ["xanax"], true),
  m("clonazepam", "benzodiazepine", ["klonopin"], true),
  m("diazepam", "benzodiazepine", ["valium"], true),
  m("lorazepam", "benzodiazepine", ["ativan"], true),
  m("temazepam", "benzodiazepine", ["restoril"]),
  m("chlordiazepoxide", "benzodiazepine", ["librium"]),
  m("buspirone", "anxiolytic", ["buspar"]),
  m("zolpidem", "sedative", ["ambien"], true),
  m("zopiclone", "sedative", ["imovane"]),
  m("eszopiclone", "sedative", ["lunesta"]),
  m("ramelteon", "sedative", ["rozerem"]),
  m("melatonin", "sleep", ["sleepwell"], true),
  m("aripiprazole", "antipsychotic", ["abilify"], true),
  m("olanzapine", "antipsychotic", ["zyprexa"], true),
  m("quetiapine", "antipsychotic", ["seroquel"], true),
  m("risperidone", "antipsychotic", ["risperdal"], true),
  m("ziprasidone", "antipsychotic", ["geodon"]),
  m("haloperidol", "antipsychotic", ["haldol"]),
  m("clozapine", "antipsychotic", ["clozaril"]),
  m("paliperidone", "antipsychotic", ["invega"]),
  m("lithium", "mood_stabilizer", ["eskalith", "lithobid"], true),
  m("valproate", "mood_stabilizer", ["valproic acid", "depakote"], true),
  m("carbamazepine", "anticonvulsant", ["tegretol"]),
  m("oxcarbazepine", "anticonvulsant", ["trileptal"]),
  m("lamotrigine", "anticonvulsant", ["lamictal"], true),
  m("topiramate", "anticonvulsant", ["topamax"], true),
  m("levetiracetam", "anticonvulsant", ["keppra"]),
  m("phenytoin", "anticonvulsant", ["dilantin"]),
  m("phenobarbital", "anticonvulsant", ["luminal"]),
  m("gabapentin", "neurologic", ["neurontin"], true),
  m("pregabalin", "neurologic", ["lyrica"], true),
  m("methylphenidate", "stimulant", ["ritalin", "concerta"], true),
  m("amphetamine", "stimulant", ["adderall"], true),
  m("lisdexamfetamine", "stimulant", ["vyvanse"]),
  m("atomoxetine", "adhd", ["strattera"], true),
  m("guanfacine", "adhd", ["intuniv", "tenex"]),
  m("levodopa", "neurologic", ["sinemet"], true),
  m("carbidopa", "neurologic", ["carbidopa levodopa"], true),
  m("pramipexole", "neurologic", ["mirapex"], true),
  m("ropinirole", "neurologic", ["requip"], true),
  m("rasagiline", "neurologic", ["azilect"]),
  m("selegiline", "neurologic", ["eldepryl"]),
  m("entacapone", "neurologic", ["comtan"]),
  m("benztropine", "neurologic", ["cogentin"]),
  m("sumatriptan", "migraine", ["imitrex"], true),
  m("rizatriptan", "migraine", ["maxalt"], true),
  m("zolmitriptan", "migraine", ["zomig"], true),
  m("eletriptan", "migraine", ["relpax"]),
  m("naratriptan", "migraine", ["amerge"]),
  m("erenumab", "migraine", ["aimovig"]),
  m("fremanezumab", "migraine", ["ajovy"]),
  m("galcanezumab", "migraine", ["emgality"]),
  m("omeprazole", "ppi", ["prilosec", "omez"], true),
  m("pantoprazole", "ppi", ["protonix", "pantocid"], true),
  m("rabeprazole", "ppi", ["aciphex"], true),
  m("esomeprazole", "ppi", ["nexium"], true),
  m("lansoprazole", "ppi", ["prevacid"]),
  m("dexlansoprazole", "ppi", ["dexilant"]),
  m("ranitidine", "h2_blocker", ["zantac"], true),
  m("famotidine", "h2_blocker", ["pepcid"], true),
  m("cimetidine", "h2_blocker", ["tagamet"]),
  m("nizatidine", "h2_blocker", ["axid"]),
  m("sucralfate", "gi", ["carafate"]),
  m("bismuth subsalicylate", "gi", ["pepto bismol"]),
  m("ondansetron", "antiemetic", ["zofran"], true),
  m("domperidone", "antiemetic", ["motilium"], true),
  m("metoclopramide", "antiemetic", ["reglan", "perinorm"]),
  m("prochlorperazine", "antiemetic", ["compazine", "stemetil"]),
  m("promethazine", "antiemetic", ["phenergan"]),
  m("loperamide", "gi", ["imodium"], true),
  m("diphenoxylate atropine", "gi", ["lomotil"]),
  m("bisacodyl", "laxative", ["dulcolax"], true),
  m("senna", "laxative", ["senokot"], true),
  m("polyethylene glycol", "laxative", ["miralax", "peg"]),
  m("lactulose", "laxative", ["duphalac"], true),
  m("docusate", "laxative", ["colace"]),
  m("psyllium", "fiber", ["metamucil", "isabgol"]),
  m("rifaximin", "gi_antibiotic", ["xifaxan"], true),
  m("mesalamine", "gi", ["asacol", "pentasa"]),
  m("sulfasalazine", "gi", ["azulfidine"]),
  m("dicyclomine", "antispasmodic", ["bentyl"]),
  m("hyoscine butylbromide", "antispasmodic", ["buscopan"]),
  m("ursodeoxycholic acid", "hepatobiliary", ["ursodiol", "udiliv"]),
  m("pancrelipase", "enzyme", ["creon"]),
  m("cetirizine", "antihistamine", ["zyrtec", "okacet"], true),
  m("levocetirizine", "antihistamine", ["xyzal"]),
  m("loratadine", "antihistamine", ["claritin"], true),
  m("desloratadine", "antihistamine", ["clarinex"]),
  m("fexofenadine", "antihistamine", ["allegra"], true),
  m("diphenhydramine", "antihistamine", ["benadryl"], true),
  m("chlorpheniramine", "antihistamine", ["chlor trimeton", "piriton"]),
  m("hydroxyzine", "antihistamine", ["atarax"], true),
  m("meclizine", "antihistamine", ["antivert"], true),
  m("betahistine", "vertigo", ["vertin"], true),
  m("montelukast", "respiratory", ["singulair", "montair"], true),
  m("zafirlukast", "respiratory", ["accolate"]),
  m("salbutamol", "bronchodilator", ["albuterol", "ventolin"], true),
  m("levalbuterol", "bronchodilator", ["xopenex"]),
  m("terbutaline", "bronchodilator", ["brethine"]),
  m("ipratropium", "bronchodilator", ["atrovent"]),
  m("tiotropium", "bronchodilator", ["spiriva"]),
  m("umeclidinium", "bronchodilator", ["incruse"]),
  m("salmeterol", "bronchodilator", ["serevent"]),
  m("formoterol", "bronchodilator", ["foradil"]),
  m("budesonide", "inhaled_corticosteroid", ["pulmicort"], true),
  m("fluticasone", "inhaled_corticosteroid", ["flixotide", "flovent"], true),
  m("beclomethasone", "inhaled_corticosteroid", ["qvar", "beclovent"]),
  m("mometasone", "inhaled_corticosteroid", ["asmanex", "nasonex"]),
  m("fluticasone salmeterol", "respiratory", ["advair", "seretide"]),
  m("budesonide formoterol", "respiratory", ["symbicort"]),
  m("guaifenesin", "respiratory", ["mucinex"]),
  m("dextromethorphan", "respiratory", ["delsym", "benadryl dm"]),
  m("prednisone", "corticosteroid", ["deltasone"], true),
  m("prednisolone", "corticosteroid", ["wysolone"], true),
  m("methylprednisolone", "corticosteroid", ["medrol"]),
  m("dexamethasone", "corticosteroid", ["decadron"], true),
  m("hydrocortisone", "corticosteroid", ["cortef"], true),
  m("betamethasone", "corticosteroid", ["celestone"]),
  m("triamcinolone", "corticosteroid", ["kenalog"]),
  m("azithromycin", "antibiotic", ["zithromax", "azee"], true),
  m("clarithromycin", "antibiotic", ["biaxin"]),
  m("erythromycin", "antibiotic", ["erythrocin"]),
  m("amoxicillin", "antibiotic", ["amoxil", "mox"], true),
  m("amoxicillin clavulanate", "antibiotic", ["augmentin", "co amoxiclav"], true),
  m("ampicillin", "antibiotic", ["principen"]),
  m("penicillin v", "antibiotic", ["veetids"]),
  m("benzathine penicillin", "antibiotic", ["bicillin"]),
  m("cloxacillin", "antibiotic", ["cloxapen"]),
  m("dicloxacillin", "antibiotic", ["dynapen"]),
  m("cephalexin", "antibiotic", ["keflex"]),
  m("cefadroxil", "antibiotic", ["duricef"]),
  m("cefuroxime", "antibiotic", ["ceftin", "zinacef"]),
  m("cefixime", "antibiotic", ["suprax"], true),
  m("cefpodoxime", "antibiotic", ["vantin"]),
  m("ceftriaxone", "antibiotic", ["rocephin"], true),
  m("ceftazidime", "antibiotic", ["fortaz"]),
  m("cefepime", "antibiotic", ["maxipime"]),
  m("meropenem", "antibiotic", ["merrem"]),
  m("imipenem cilastatin", "antibiotic", ["primaxin"]),
  m("ertapenem", "antibiotic", ["invanz"]),
  m("ciprofloxacin", "antibiotic", ["cipro"], true),
  m("levofloxacin", "antibiotic", ["levaquin"], true),
  m("moxifloxacin", "antibiotic", ["avelox"]),
  m("ofloxacin", "antibiotic", ["floxin"]),
  m("doxycycline", "antibiotic", ["vibramycin"], true),
  m("minocycline", "antibiotic", ["minocin"]),
  m("tetracycline", "antibiotic", ["sumycin"]),
  m("clindamycin", "antibiotic", ["cleocin"], true),
  m("linezolid", "antibiotic", ["zyvox"], true),
  m("vancomycin", "antibiotic", ["vancocin"], true),
  m("daptomycin", "antibiotic", ["cubicin"]),
  m("metronidazole", "antibiotic", ["flagyl"], true),
  m("tinidazole", "antibiotic", ["fasigyn"], true),
  m("nitrofurantoin", "antibiotic", ["macrobid"]),
  m("fosfomycin", "antibiotic", ["monurol"]),
  m("trimethoprim sulfamethoxazole", "antibiotic", ["bactrim", "septra", "cotrimoxazole"]),
  m("trimethoprim", "antibiotic", ["proloprim"]),
  m("gentamicin", "antibiotic", ["garamycin"]),
  m("amikacin", "antibiotic", ["amikin"]),
  m("tobramycin", "antibiotic", ["tobrex"]),
  m("rifampin", "antibiotic", ["rifampicin", "rifadin"]),
  m("isoniazid", "antitubercular", ["inh"]),
  m("ethambutol", "antitubercular", ["myambutol"]),
  m("pyrazinamide", "antitubercular", ["pza"]),
  m("fluconazole", "antifungal", ["diflucan"], true),
  m("itraconazole", "antifungal", ["sporanox"]),
  m("voriconazole", "antifungal", ["vfend"]),
  m("posaconazole", "antifungal", ["noxafil"]),
  m("clotrimazole", "antifungal", ["canesten"], true),
  m("ketoconazole", "antifungal", ["nizoral"], true),
  m("terbinafine", "antifungal", ["lamisil"]),
  m("nystatin", "antifungal", ["mycostatin"]),
  m("amphotericin b", "antifungal", ["fungizone"]),
  m("acyclovir", "antiviral", ["zovirax"], true),
  m("valacyclovir", "antiviral", ["valtrex"], true),
  m("famciclovir", "antiviral", ["famvir"]),
  m("oseltamivir", "antiviral", ["tamiflu"], true),
  m("remdesivir", "antiviral", ["veklury"], true),
  m("ivermectin", "antiparasitic", ["stromectol"], true),
  m("albendazole", "antiparasitic", ["zentel"]),
  m("mebendazole", "antiparasitic", ["vermox"]),
  m("praziquantel", "antiparasitic", ["biltricide"]),
  m("chloroquine", "antimalarial", ["aralen"]),
  m("artemether lumefantrine", "antimalarial", ["coartem"]),
  m("atovaquone proguanil", "antimalarial", ["malarone"]),
  m("levothyroxine", "thyroid", ["synthroid", "thyronorm", "eltroxin"], true),
  m("liothyronine", "thyroid", ["cytomel"]),
  m("methimazole", "thyroid", ["tapazole"], true),
  m("propylthiouracil", "thyroid", ["ptu"], true),
  m("iodine", "thyroid", ["lugol iodine"]),
  m("vitamin d", "vitamin", ["cholecalciferol", "vitamin d3"], true),
  m("ergocalciferol", "vitamin", ["vitamin d2"]),
  m("vitamin b12", "vitamin", ["cyanocobalamin", "methylcobalamin"], true),
  m("folic acid", "vitamin", ["folate"], true),
  m("thiamine", "vitamin", ["vitamin b1"]),
  m("pyridoxine", "vitamin", ["vitamin b6"]),
  m("riboflavin", "vitamin", ["vitamin b2"]),
  m("niacinamide", "vitamin", ["nicotinamide"]),
  m("ascorbic acid", "vitamin", ["vitamin c"]),
  m("vitamin e", "vitamin", ["tocopherol"]),
  m("vitamin k", "vitamin", ["phytonadione"]),
  m("iron", "mineral", ["ferrous sulfate", "ferrous fumarate"], true),
  m("calcium carbonate", "mineral", ["caltrate"], true),
  m("calcium citrate", "mineral", ["citracal"]),
  m("magnesium", "mineral", ["magnesium oxide", "magnesium glycinate"], true),
  m("potassium chloride", "mineral", ["kcl", "klor con"]),
  m("zinc", "mineral", ["zinc sulfate"]),
  m("alendronate", "bisphosphonate", ["fosamax"], true),
  m("risedronate", "bisphosphonate", ["actonel"]),
  m("ibandronate", "bisphosphonate", ["boniva"]),
  m("zoledronic acid", "bisphosphonate", ["reclast", "zometa"]),
  m("denosumab", "bone", ["prolia", "xgeva"]),
  m("teriparatide", "bone", ["forteo"]),
  m("raloxifene", "bone", ["evista"]),
  m("sildenafil", "urology", ["viagra"], true),
  m("tadalafil", "urology", ["cialis"], true),
  m("vardenafil", "urology", ["levitra"], true),
  m("avanafil", "urology", ["stendra"]),
  m("finasteride", "urology", ["propecia", "proscar"], true),
  m("dutasteride", "urology", ["avodart"], true),
  m("tamsulosin", "urology", ["flomax"], true),
  m("silodosin", "urology", ["rapaflo"]),
  m("alfuzosin", "urology", ["uroxatral"]),
  m("oxybutynin", "urology", ["ditropan"], true),
  m("tolterodine", "urology", ["detrol"]),
  m("solifenacin", "urology", ["vesicare"]),
  m("mirabegron", "urology", ["myrbetriq"], true),
  m("desmopressin", "urology", ["ddavp"]),
  m("phenazopyridine", "urology", ["pyridium"]),
  m("ethinyl estradiol", "hormonal", ["estrogen pill"]),
  m("levonorgestrel", "hormonal", ["plan b", "mirena"]),
  m("medroxyprogesterone", "hormonal", ["depo provera", "provera"]),
  m("norethindrone", "hormonal", ["aygestin"]),
  m("progesterone", "hormonal", ["prometrium"]),
  m("estradiol", "hormonal", ["estrace", "vivelle"]),
  m("testosterone", "hormonal", ["androgel", "testim"]),
  m("clomiphene", "fertility", ["clomid"]),
  m("letrozole", "fertility", ["femara"]),
  m("colchicine", "rheumatology", ["colcrys"], true),
  m("allopurinol", "rheumatology", ["zyloprim"], true),
  m("febuxostat", "rheumatology", ["uloric"]),
  m("probenecid", "rheumatology", ["benemid"]),
  m("methotrexate", "immunosuppressant", ["trexall"], true),
  m("hydroxychloroquine", "immunosuppressant", ["plaquenil"], true),
  m("anakinra", "biologic", ["kineret"]),
  m("leflunomide", "immunosuppressant", ["arava"]),
  m("azathioprine", "immunosuppressant", ["imuran"]),
  m("mycophenolate", "immunosuppressant", ["cellcept", "myfortic"]),
  m("cyclosporine", "immunosuppressant", ["sandimmune", "neoral"], true),
  m("tacrolimus", "immunosuppressant", ["prograf"], true),
  m("sirolimus", "immunosuppressant", ["rapamune"]),
  m("adalimumab", "biologic", ["humira"], true),
  m("infliximab", "biologic", ["remicade"], true),
  m("etanercept", "biologic", ["enbrel"], true),
  m("certolizumab", "biologic", ["cimzia"]),
  m("golimumab", "biologic", ["simponi"]),
  m("ustekinumab", "biologic", ["stelara"]),
  m("secukinumab", "biologic", ["cosentyx"]),
  m("ixekizumab", "biologic", ["taltz"]),
  m("tocilizumab", "biologic", ["actemra"]),
  m("rituximab", "biologic", ["rituxan", "mabthera"]),
  m("abatacept", "biologic", ["orencia"]),
  m("baricitinib", "immunosuppressant", ["olumiant"]),
  m("tofacitinib", "immunosuppressant", ["xeljanz"]),
  m("upadacitinib", "immunosuppressant", ["rinvoq"]),
  m("apremilast", "immunosuppressant", ["otezla"]),
  m("isotretinoin", "dermatology", ["accutane", "roaccutane"]),
  m("tretinoin", "dermatology", ["retin a"]),
  m("adapalene", "dermatology", ["differin"]),
  m("benzoyl peroxide", "dermatology", ["benzac"]),
  m("clobetasol", "dermatology", ["temovate"]),
  m("mometasone topical", "dermatology", ["elocon"]),
  m("betamethasone topical", "dermatology", ["diprolene"]),
  m("calcipotriene", "dermatology", ["dovonex"]),
  m("pimecrolimus", "dermatology", ["elidel"]),
  m("dupilumab", "biologic", ["dupixent"]),
  m("latanoprost", "ophthalmic", ["xalatan"]),
  m("timolol ophthalmic", "ophthalmic", ["timoptic"]),
  m("dorzolamide", "ophthalmic", ["trusopt"]),
  m("brimonidine", "ophthalmic", ["alphagan"]),
  m("travoprost", "ophthalmic", ["travatan"]),
  m("cyclosporine ophthalmic", "ophthalmic", ["restasis"]),
  m("artificial tears", "ophthalmic", ["refresh", "systane"]),
  m("tamoxifen", "oncology", ["nolvadex"]),
  m("anastrozole", "oncology", ["arimidex"]),
  m("fulvestrant", "oncology", ["faslodex"]),
  m("exemestane", "oncology", ["aromasin"]),
  m("bicalutamide", "oncology", ["casodex"]),
  m("leuprolide", "oncology", ["lupron"]),
  m("goserelin", "oncology", ["zoladex"]),
  m("imatinib", "oncology", ["gleevec", "glivec"]),
  m("dasatinib", "oncology", ["sprycel"]),
  m("nilotinib", "oncology", ["tasigna"]),
  m("erlotinib", "oncology", ["tarceva"]),
  m("gefitinib", "oncology", ["iressa"]),
  m("osimertinib", "oncology", ["tagrisso"]),
  m("capecitabine", "oncology", ["xeloda"]),
  m("pemetrexed", "oncology", ["alimta"]),
  m("cyclophosphamide", "oncology", ["cytoxan"]),
  m("doxorubicin", "oncology", ["adriamycin"]),
  m("paclitaxel", "oncology", ["taxol"]),
  m("docetaxel", "oncology", ["taxotere"]),
  m("carboplatin", "oncology", ["paraplatin"]),
  m("cisplatin", "oncology", ["platinol"]),
  m("oxaliplatin", "oncology", ["eloxatin"]),
  m("5 fluorouracil", "oncology", ["fluorouracil", "5 fu"]),
  m("gemcitabine", "oncology", ["gemzar"]),
  m("pembrolizumab", "oncology", ["keytruda"]),
  m("nivolumab", "oncology", ["opdivo"]),
  m("ipilimumab", "oncology", ["yervoy"]),
  m("bevacizumab", "oncology", ["avastin"]),
  m("trastuzumab", "oncology", ["herceptin"]),
  m("olaparib", "oncology", ["lynparza"]),
  m("palbociclib", "oncology", ["ibrance"]),
  m("lenalidomide", "oncology", ["revlimid"]),
  m("bortezomib", "oncology", ["velcade"]),
  m("hydroxyurea", "hematology", ["hydrea"]),
  m("deferasirox", "hematology", ["exjade", "jadenu"]),
  m("epoetin alfa", "hematology", ["epogen", "procrit"]),
  m("filgrastim", "hematology", ["neupogen"]),
  m("tranexamic acid", "hematology", ["lysteda", "pause"]),
  m("cinnarizine", "vertigo", ["stugeron"]),
  m("scopolamine", "vertigo", ["transderm scop"]),
  m("varenicline", "smoking_cessation", ["chantix", "champix"]),
  m("nicotine replacement", "smoking_cessation", ["nicotine patch", "nicorette"]),
  m("orlistat", "weight", ["xenical", "alli"]),
  m("phentermine", "weight", ["adipex"]),
  m("miglitol", "antidiabetic", ["glyset"]),
  m("donepezil", "neurologic", ["aricept"]),
  m("rivastigmine", "neurologic", ["exelon"]),
  m("memantine", "neurologic", ["namenda"]),
  m("galantamine", "neurologic", ["razadyne"]),
  m("baclofen", "muscle_relaxant", ["lioresal"]),
  m("cyclobenzaprine", "muscle_relaxant", ["flexeril"]),
  m("tizanidine", "muscle_relaxant", ["zanaflex"]),
  m("methocarbamol", "muscle_relaxant", ["robaxin"]),
  m("orphenadrine", "muscle_relaxant", ["norflex"]),
  m("rocuronium", "anesthesia", ["zemuron"]),
  m("propofol", "anesthesia", ["diprivan"]),
  m("ketamine", "anesthesia", ["ketalar"]),
  m("midazolam", "benzodiazepine", ["versed"]),
  m("fexofenadine pseudoephedrine", "antihistamine", ["allegra d"]),
  m("pseudoephedrine", "decongestant", ["sudafed"]),
  m("phenylephrine", "decongestant", ["neo synephrine"]),
  m("fluticasone nasal", "nasal_steroid", ["flonase"]),
  m("azelastine", "nasal_antihistamine", ["astepro"]),
  m("olopatadine", "ophthalmic", ["patanol"]),
  m("mupirocin", "dermatology", ["bactroban"]),
  m("silver sulfadiazine", "dermatology", ["silvadene"]),
  m("permethrin", "dermatology", ["elimite"]),
  m("malathion", "dermatology", ["ovide"]),
];

export function normalizeMedToken(s) {
  return String(s || "")
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function findMedicationByLabel(label) {
  const n = normalizeMedToken(label);
  return MEDICATION_GENERICS.find((m) => m.search_terms.includes(n));
}
